[package]
name = "finebot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.4"
lazy-init = "0.5"
websocket = "0.26"